import type { Metadata } from 'next';
import { ich1q, zenkaku } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${zenkaku.variable} ${ich1q.variable} font-zenkaku`}>
        {children}
      </body>
    </html>
  );
}
