import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const notoSans = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  weight: 'variable',
  display: 'swap',
});

const mono = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-mono-sans',
  weight: 'variable',
  display: 'swap',
});

const ich1q = localFont({
  src: './ich1Q-hand-Regular.ttf',
  variable: '--font-ich1q',
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSans.variable} ${mono.variable} ${ich1q.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
